# .github/workflows/eurodyssey-monitor.yml
name: EurOdyssey Traineeship Monitor

on:
  schedule:
    # Run every 2 hours (GitHub Actions uses UTC time)
    - cron: '0 */2 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 schedule lxml
        
    - name: Run traineeship monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python eurodyssey_monitor_github.py
        
    - name: Commit and push CSV updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add eurodyssey_traineeships.csv
        git diff --staged --quiet || git commit -m "Update traineeships data - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}